'use strict';

/**
 * Offentlige butikksider som PokéInventar kan prøve å lese produktdata fra.
 *
 * adapter: "auto" prøver Shopify Ajax API, WooCommerce Store API og til slutt
 * butikkens egen søkeside. Produktlenker godtas bare når de peker til butikkens
 * eget domene.
 */
module.exports = [
  ['Cardcenter', 'https://cardcenter.no'],
  ['Pokestore', 'https://pokestore.no'],
  ['Retroworld', 'https://retroworld.no'],
  ['Boosterpakker', 'https://boosterpakker.no'],
  ['LABOGE', 'https://laboge.no'],
  ['CardCollect', 'https://cardcollect.no'],
  ['CDON', 'https://cdon.no'],
  ['KanonCon', 'https://kanoncon.no'],
  ['PokeNordic', 'https://pokenordic.no'],
  ['LCG Cards', 'https://lcgcards.no'],
  ['Pokebua', 'https://pokebua.no'],
  ['Wasteland', 'https://wasteland.no'],
  ['Maeddiiss', 'https://maeddiiss.no'],
  ['Pokelageret', 'https://pokelageret.no'],
  ['Mythic', 'https://mythic.no'],
  ['Cardhouse', 'https://cardhouse.no'],
  ['Pokefriends', 'https://pokefriends.no'],
  ['Packs of Norway', 'https://packsofnorway.no'],
  ['Playlot', 'https://playlot.no'],
  ['BoosterKongen', 'https://boosterkongen.no'],
  ['Pokecandy', 'https://pokecandy.no'],
  ['Kidsa', 'https://kidsa.no'],
  ['Ringo', 'https://ringo.no'],
  ['Spillmonster', 'https://spillmonster.no'],
  ['Braspill', 'https://braspill.no'],
  ['MaxGaming', 'https://www.maxgaming.no'],
  ['Card Kings', 'https://cardkings.no'],
  ['Poke-Shop', 'https://poke-shop.no'],
  ['EpiCards', 'https://epicards.no'],
  ['Norli', 'https://www.norli.no'],
  ['Loot Lagoon', 'https://lootlagoon.no'],
  ['Alt av Spill', 'https://altavspill.no'],
  ['Altakube', 'https://altakube.no'],
  ['Platekompaniet', 'https://www.platekompaniet.no'],
  ['Pokekort', 'https://pokekort.no'],
  ['Game Ninja', 'https://gameninja.no'],
  ['Collectors Corner', 'https://collectorscorner.no'],
  ['CardDex', 'https://carddex.no'],
  ['Linne Elektronikk', 'https://linneelektronikk.no'],
  ['TCG Norge', 'https://tcgnorge.no'],
  ['Extra Leker', 'https://www.extra-leker.no'],
  ['Livet er kort', 'https://liveterekort.no'],
  ['Neo Tokyo', 'https://neo-tokyo.no'],
  ['Gamezone', 'https://gamezone.no'],
  ['Mystic Trades', 'https://mystictrades.no'],
  ['Nille', 'https://www.nille.no'],
  ['Emken', 'https://emken.no'],
  ['Outland', 'https://www.outland.no'],
  ['King of Breaks', 'https://kingofbreaks.no'],
  ['Jollyroom', 'https://www.jollyroom.no'],
  ['PokeWorld', 'https://pokeworld.no'],
  ['Hatamon TCG', 'https://hatamontcg.no'],
  ['Midgard Games', 'https://midgardgames.no'],
  ['Pokéchest', 'https://pokechest.no'],
  ['Lekekassen', 'https://lekekassen.no'],
  ['Proshop', 'https://www.proshop.no'],
  ['Poki-Heaven', 'https://poki-heaven.no'],
  ['PokéBoks', 'https://pokeboks.no'],
  ['Pokemadness', 'https://www.pokemadness.no'],
  ['CS Megastore', 'https://csmegastore.no'],
  ['Game and Trade', 'https://gameandtrade.no'],
  ['Poku', 'https://www.poku.no'],
  ['Collectible', 'https://www.collectible.no'],
  ['24CollectCards', 'https://24collectcards.no'],
  ['Lekegiganten', 'https://lekegiganten.no'],
  ['NorthTCG', 'https://northtcg.no'],
  ['Spillbua', 'https://spillbua.no'],
  ['Pokesingles', 'https://pokesingles.no'],
  ['Cardstore', 'https://cardstore.no'],
  ['Arctic Loot', 'https://arcticloot.no'],
  ['Lirum Larum Leg', 'https://www.lirumlarumleg.no'],
  ['Panduro', 'https://panduro.com/nb-no'],
  ['Pokeplug', 'https://pokeplug.no'],
  ['Sprell', 'https://www.sprell.no'],
  ['Gamingsjappa', 'https://gamingsjappa.no'],
  ['Pokelink', 'https://pokelink.no'],
  ['Lekis', 'https://lekis.no'],
  ['Pokehandel', 'https://pokehandel.no'],
  ['Pokehuset', 'https://pokehuset.no'],
  ["ruru's cardhouse", 'https://ruruscardhouse.no'],
  ['Poke4dayz', 'https://www.poke4dayz.no']
].map(([name, baseUrl]) => ({
  name,
  baseUrl,
  adapter: 'auto',
  enabled: true,
  searchPaths: [
    '/search?q={query}&type=product',
    '/?s={query}&post_type=product',
    '/search?query={query}'
  ]
}));
